# Generated by Django 6.0.3 on 2026-05-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='use_team_theme',
            field=models.BooleanField(default=False),
        ),
    ]
