# Generated by Django 6.0.3 on 2026-06-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprofile_use_team_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_primary',
            field=models.CharField(default='#e10600', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_secondary',
            field=models.CharField(default='#c40500', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_text',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_mode',
            field=models.CharField(choices=[('classic', 'Classic F1 (Red)'), ('team', 'Favorite Team Colors'), ('driver', 'Favorite Driver Accent'), ('custom', 'Custom Personal Theme')], default='classic', max_length=20),
        ),
    ]
