# Generated by Django 6.0.3 on 2026-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userprofile_custom_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_watermark',
            field=models.BooleanField(default=True),
        ),
    ]
